### ISSUE TITLE
C++ improvement: change doxygen documentation comments from sources to headers.

### ISSUE THREAD

**Issue by Fare9** [Fare9/KUNAI-static-analyzer#15]
Just cut/paste comments of doxygen from source files to header files. Very easy to do!

**Comment by anmolrajsoni15** [comment]
Hello, I am new to github. I can solve this issue, just tell me the location of your files in the repo.

**Comment by Fare9** [comment]
Hello, thanks for your interest, I think in most of the files I could apply a fix to this issue, but some of the headers from DEX parser have no  documentation yet, and it would be great to have a page on Doxygen for them, you can find the headers in here: https://github.com/Fare9/KUNAI-static-analyzer/tree/main/src/includes/KUNAI/DEX/parser
Most of the necessary documentation is straightforward, and the headers are explained at the beginning of the file.

Thank you very much!

Do not hesitate to contact me for any question.
