### ISSUE TITLE
Rewrite new parser for MethodID

### ISSUE THREAD

**Issue by Fare9** [Fare9/KUNAI-static-analyzer#59]
Write a new parser for the DEX Methods and the `MethodID`, this has to follow the convention from the other parsers (strings, types, protos, fields...), once the class is created, it must be included to `Parser` class, and also a function like `parse_methods` must be included in the `Method` class and must be called from the `Parser` function `parse_file`. Use the branch https://github.com/Fare9/KUNAI-static-analyzer/tree/refactoring for it, and once it is everything included, the code must compile properly, and also the unit-test from the parser must run without crashing.

**Comment by javaernesto** [comment]
Add new Methods Parser [a6d7706f0b97469a4a264fd71c35c20a2fd8ccd0](https://github.com/Fare9/KUNAI-static-analyzer/commit/a6d7706f0b97469a4a264fd71c35c20a2fd8ccd0)

**Comment by Fare9** [comment]
Added a Pretty Printer and code checked: https://github.com/Fare9/KUNAI-static-analyzer/commit/4ca153d14915dc8a5df453282a47e1146d9aec6e. Everything working properly after a fix!
